name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cg90cf1mbg5eco8nucug"
        retries: 20
        wait: 16000
        sleep: 30000
