# Script to deploy on the Render cloud platform

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook
      with: 
        url: ${{secrets.DEPLOY_HOOK_URL}}

    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} # This is the GitHub account token
        service-id: "srv-cg9ghoseooghng0b9o70" # This id is unique for each app
        retries: 20
        wait: 16000
        sleep: 30000
